---

 - hosts: all
   become: true
   pre_tasks:

   - name: install updates (Rocky)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "Rocky"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

 - hosts: workstations
   become: true
   tasks:

   - name: install unzip
     tags: ubuntu,desktop
     package:
       name: unzip

   - name: install terraform
     tags: ubuntu,desktop
     unarchive:
       src: https://releases.hashicorp.com/terraform/1.14.1/terraform_1.14.1_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root

 - hosts: web_servers
   become: true
   tasks:

   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: install apache and php for Rocky servers
     tags: apache,httpd,rocky
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "Rocky"

   - name: copy default html file
     tags: apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644


 - hosts: db_servers
   become: true
   tasks:

   - name: install Mariadb Rocky
     tags: rocky,db,mariadb
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "Rocky"

   - name: install Mariadb Ubuntu
     tags: ubuntu,db,mariadb
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"

 -  hosts: file_servers
    become: true
    tasks:

    - name: install samba
      tags: samba
      package:
        name: samba
        state: latest

